// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlUtHxx8wMVxUnugnsRkVv7VzPxnFkIU',
    appId: '1:905710900998:web:2fbb807c3d7124ca613087',
    messagingSenderId: '905710900998',
    projectId: 'pocket-buddy-b54fb',
    authDomain: 'pocket-buddy-b54fb.firebaseapp.com',
    storageBucket: 'pocket-buddy-b54fb.appspot.com',
    measurementId: 'G-MGE54TNXPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtavbzedXM3V_mhpyIJA--JO1NvdR5rao',
    appId: '1:905710900998:android:f0fd5217abbd0d81613087',
    messagingSenderId: '905710900998',
    projectId: 'pocket-buddy-b54fb',
    storageBucket: 'pocket-buddy-b54fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FAjxU8ROAlHGyCFarpKJ0CxWGwNEcss',
    appId: '1:905710900998:ios:7f0805d96668ded9613087',
    messagingSenderId: '905710900998',
    projectId: 'pocket-buddy-b54fb',
    storageBucket: 'pocket-buddy-b54fb.appspot.com',
    androidClientId: '905710900998-3gcppnqknqsdej8us82lrgao0tlsmk85.apps.googleusercontent.com',
    iosClientId: '905710900998-tumsk1g2ni4rfqbkc0498k8uaq7l0j0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketbuddy',
  );
}
